-- =====================================================
-- CampFlow PMS - Row Level Security (RLS)
-- =====================================================
-- File: 07_rls.sql
-- Purpose: Security policies for multi-user access control
-- Execution Order: 7th (last migration file)
-- Status: PLACEHOLDER - Implementation planned for Phase 2
-- =====================================================

-- =====================================================
-- CURRENT STATE (Phase 1 - MVP)
-- =====================================================
-- RLS is currently DISABLED for all tables
-- The application uses service role key for all operations
-- This is acceptable for internal-only usage (reception staff)
--
-- Security measures in place:
-- - API routes are server-side only (not exposed to browser)
-- - Environment variables not committed to git
-- - Supabase project dashboard access restricted

-- =====================================================
-- FUTURE IMPLEMENTATION (Phase 2)
-- =====================================================
-- When implementing multi-user authentication:
--
-- 1. CREATE USER ROLES TABLE
-- CREATE TABLE user_roles (
--   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--   user_id UUID NOT NULL REFERENCES auth.users(id),
--   role VARCHAR(20) NOT NULL CHECK (role IN ('admin', 'reception', 'customer')),
--   created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
-- );
--
-- 2. ENABLE RLS ON ALL TABLES
-- ALTER TABLE pitches ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE booking_guests ENABLE ROW LEVEL SECURITY;
--
-- 3. CREATE POLICIES
--
-- -- Admin: Full access to all tables
-- CREATE POLICY admin_all_pitches ON pitches
--   FOR ALL USING (
--     EXISTS (
--       SELECT 1 FROM user_roles 
--       WHERE user_id = auth.uid() AND role = 'admin'
--     )
--   );
--
-- -- Reception: Read/write access to bookings and customers
-- CREATE POLICY reception_bookings ON bookings
--   FOR ALL USING (
--     EXISTS (
--       SELECT 1 FROM user_roles 
--       WHERE user_id = auth.uid() AND role IN ('admin', 'reception')
--     )
--   );
--
-- -- Customer: Read-only access to their own bookings
-- CREATE POLICY customer_own_bookings ON bookings
--   FOR SELECT USING (
--     customer_id IN (
--       SELECT customer_id FROM customer_users 
--       WHERE user_id = auth.uid()
--     )
--   );
--
-- 4. CREATE CUSTOMER-USER MAPPING TABLE
-- CREATE TABLE customer_users (
--   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--   customer_id UUID NOT NULL REFERENCES customers(id),
--   user_id UUID NOT NULL REFERENCES auth.users(id),
--   created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
--   UNIQUE(customer_id, user_id)
-- );

-- =====================================================
-- NOTES FOR PHASE 2 IMPLEMENTATION
-- =====================================================
-- Priority order:
-- 1. Implement Supabase Auth (email/password)
-- 2. Create user_roles table and seed admin user
-- 3. Enable RLS on all tables
-- 4. Create policies for each role
-- 5. Update API routes to use auth.uid() instead of service role
-- 6. Add middleware to verify JWT tokens
-- 7. Implement customer portal (optional)
--
-- Testing checklist:
-- - Verify admin can access all data
-- - Verify reception can create/edit bookings
-- - Verify customers can only view their bookings
-- - Verify unauthenticated users are denied access

-- =====================================================
-- END OF RLS PLACEHOLDER
-- =====================================================
-- This file intentionally left mostly empty
-- No actions required for Phase 1 deployment
